project_id = "bbrmjrjorcgsgeztzbsr"

[functions.webhook-mercadopago]
verify_jwt = false

[functions.webhook-n8n-payment]
verify_jwt = false

[functions.webhook-auth-events]
verify_jwt = false

[functions.api-produtos-cadastrar]
verify_jwt = false

[functions.api-produtos-listar]
verify_jwt = false

[functions.api-categorias-listar]
verify_jwt = false

[functions.api-categorias-cadastrar]
verify_jwt = false

[functions.api-subcategorias-listar]
verify_jwt = false

[functions.api-subcategorias-cadastrar]
verify_jwt = false